### PR TITLE
replaced jcenter repo with mavenCentral repo

### PR DESCRIPTION
**Pull request by razvanstanga**
app does not longer build with jcenter repo

### CODE REVIEW

**Comment by davidbooth** [comment]
Confirmed. This fixes build issues for me as well.

**Comment by Samsebamse** [comment]
Actually I got error building the code now. Worked fine on friday.
image

**Comment by wfairclough** [comment]
This fixes the issue for me as well.

**Comment by Samsebamse** [comment]
My mistake. This fixes the issue ;)

**Comment by vinay2897** [comment]
Thanks man. Spent hours on this.

**Comment by bigleesan** [comment]
Hi. Andrehtissot 
Very nice your plugin. I thank so much.
Is there any way to get only one push message from the same person in the background?
Icons appear as many as sent now.
And to work with the plugin below?
   cordova-plugin-local-notifications

Thanks.

**Pull request merged**
