### PR TITLE
[FCM] Update API to 18.0.0+

### PR DESCRIPTION
**Pull request by mfdeveloper**
### Android

- Refactor to use FCM `com.google.firebase:firebase-messaging` version `18.0.0`+

- Refactor to can use this plugin directly from Android Native (without a Cordova Webview). This is great to call `getToken()` from a Android native project, for example.

- Added a example project under `android` folder, and deliver this plugin like a dependency with https://jitpack.io

- `FCMPlugin.gradle` improvements to allow use this plugin with `cordova-android` versions `6.3.0` and `8.0.0`+. These changes was required after upgrade the `firebase-messaging` dependency.

### IOS

- Added https://cocoapods.org support

### CODE REVIEW

**Comment by Radecom** [comment]
Worked for me without a problem!

**Comment by andrehtissot** [comment]
PR accepted. But I'll add some small changes before getting it to master.

Thank you!

**Comment by mfdeveloper** [comment]
> PR accepted. But I'll add some small changes before getting it to master.
> 
> Thank you!

Maaany thanks **@andrehtissot**! Please, when you add these changes into **[master]** and publish a new release of this plugin to https://npmjs.com, send a message to me. After that, I will upgrade my project to use your repo :smiley:

**Comment by andrehtissot** [comment]
Released as 3.0.0. Please check it out.

**Pull request merged**
